[package]
name = "Cryptosampleenclave"
version = "1.0.0"
authors = ["The Teaclave Authors"]

[lib]
name = "cryptosampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_trts = { path = "../../../sgx_trts" }
sgx_tstd = { path = "../../../sgx_tstd" }
sgx_tcrypto = { path = "../../../sgx_tcrypto" }
