[package]
name = "enclave1"
version = "1.0.0"
authors = ["The Teaclave Authors"]

[lib]
name = "enclave1"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }

[dependencies]
attestation = {path = "../attestation/"}
