[package]
name = "attestation"
version = "1.0.0"
authors = ["The Teaclave Authors"]

[features]
default = []
use_std = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_trts = { path = "../../../sgx_trts" }
sgx_tstd = { path = "../../../sgx_tstd" }
sgx_tdh = { path = "../../../sgx_tdh" }
